USE [master]
GO

IF(EXISTS(SELECT * FROM sysdatabases WHERE name = 'CineClick'))
Begin
	ALTER DATABASE [CineClick] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE [CineClick]
END
GO

CREATE DATABASE [CineClick]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CineClick', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\CineClick.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CineClick_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\CineClick_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [CineClick] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CineClick].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CineClick] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CineClick] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CineClick] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CineClick] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CineClick] SET ARITHABORT OFF 
GO
ALTER DATABASE [CineClick] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [CineClick] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CineClick] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CineClick] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CineClick] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CineClick] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CineClick] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CineClick] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CineClick] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CineClick] SET  ENABLE_BROKER 
GO
ALTER DATABASE [CineClick] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CineClick] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CineClick] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CineClick] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CineClick] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CineClick] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CineClick] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CineClick] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CineClick] SET  MULTI_USER 
GO
ALTER DATABASE [CineClick] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CineClick] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CineClick] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CineClick] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [CineClick] SET DELAYED_DURABILITY = DISABLED 
GO
USE [CineClick]
GO
/****** Object:  Table [dbo].[Filme]    Script Date: 23/01/2017 16:39:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Filme](
	[Id] [uniqueidentifier] ,
	[Nome] [varchar](50) NOT NULL,
	[Sinopse] [varchar](300) NULL,
	[InicioDoPeriodo] [datetime] NOT NULL,
	[FimDoPeriodo] [datetime] NOT NULL,
	[NivelDeClassificacao] [varchar](2) NOT NULL,
	[CadastradoEm] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Ingresso]    Script Date: 23/01/2017 16:39:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ingresso](
	[Id] [uniqueidentifier],
	[SessaoId] [uniqueidentifier]  NULL,
	[Valor] [decimal](18, 0) NULL,
	[Tipo] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Programacao]    Script Date: 23/01/2017 16:39:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Programacao](
	[Id] [uniqueidentifier],
	[Inicio] [datetime] NOT NULL,
	[Fim] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Sala]    Script Date: 23/01/2017 16:39:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Sala](
	[Id] [uniqueidentifier],
	[Descricao] [varchar](50) NULL,
	[Capacidade] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Sessao]    Script Date: 23/01/2017 16:39:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sessao](
	[Id] [uniqueidentifier] ,
	[FilmeId] [uniqueidentifier]  NULL,
	[SalaId]  [uniqueidentifier] null,
	[ProgramacaoId] [uniqueidentifier] NULL,	
	[VendasRealizadas] [int] NOT NULL,
	[Disponivel] [bit] NOT NULL,
	[Data] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Ingresso]  WITH CHECK ADD  CONSTRAINT [Fk_Sessao] FOREIGN KEY([SessaoId])
REFERENCES [dbo].[Sessao] ([Id])  ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Ingresso] CHECK CONSTRAINT [Fk_Sessao]
GO
ALTER TABLE [dbo].[Sessao]  WITH CHECK ADD  CONSTRAINT [Fk_filme] FOREIGN KEY([FilmeId])
REFERENCES [dbo].[Filme] ([Id]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Sessao] CHECK CONSTRAINT [Fk_filme]
GO
ALTER TABLE [dbo].[Sessao]  WITH CHECK ADD  CONSTRAINT [fk_programacao] FOREIGN KEY([ProgramacaoId])
REFERENCES [dbo].[Programacao] ([Id]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Sessao] CHECK CONSTRAINT [fk_programacao]
GO
ALTER TABLE [dbo].[Sessao]  WITH CHECK ADD  CONSTRAINT [Fk_salas] FOREIGN KEY([SalaId])
REFERENCES [dbo].[Sala] ([Id]) ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Sessao] CHECK CONSTRAINT [Fk_salas]   
GO
USE [master]
GO
ALTER DATABASE [CineClick] SET  READ_WRITE  
GO

use master

go

ALTER AUTHORIZATION ON DATABASE::Cineclick TO [sa];